import Link from "next/link";
import { LoopDiagram } from "@/components/LoopDiagram";
import { BadgeLegend } from "@/components/EvidenceBadge";
import { Panel } from "@/components/Panel";

export default function Home() {
  return (
    <div className="mx-auto max-w-[1500px] px-5 py-10">
      <section className="mb-10 max-w-4xl">
        <p className="eyebrow mb-2">Climate digital twins</p>
        <h1 className="text-[34px] font-semibold leading-[1.1] tracking-tight">
          A twin is only useful if it can be{" "}
          <span className="text-accent">acted on</span> — and only safe if it
          knows what it cannot promise.
        </h1>
        <p className="mt-4 text-[14.5px] leading-relaxed text-ink-mute">
          PSPE perceives a hazard&apos;s state under partial observation, carries
          it forward under the governing physics, and plans interventions against
          a hard limit with a calibrated safety margin. This portal shows what
          each half of that claim rests on: the perception and dynamics are
          scored against independent references, and the intervention effects are
          projections that no observational record can confirm.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="eyebrow mb-3">The loop</h2>
        <LoopDiagram />
      </section>

      <section className="mb-10 grid gap-4 lg:grid-cols-2">
        <Panel eyebrow="Flood" title="2022 Northern Rivers, NSW">
          <p className="mb-3 text-[13px] leading-relaxed text-ink-mute">
            A 32 km reach of the lower Richmond River during Australia&apos;s
            costliest flood. Our solver reproduces the reference at{" "}
            <b className="text-ink">CSI 0.979</b>. Half the candidate levees make
            flooding <b className="text-bad">worse</b>.
          </p>
          <Link href="/methodology/flood" className="text-[13px] text-accent hover:underline">
            Open the flood twin →
          </Link>
        </Panel>
        <Panel eyebrow="Safety" title="When a margin is usable">
          <p className="mb-3 text-[13px] leading-relaxed text-ink-mute">
            A calibrated margin only fits when the hazard&apos;s spread is small
            against the gain an intervention buys. That is a checkable
            precondition, not a hope.
          </p>
          <Link href="/methodology/margin" className="text-[13px] text-accent hover:underline">
            Open the margin explorer →
          </Link>
        </Panel>
      </section>

      <section className="mb-4">
        <h2 className="eyebrow mb-3">How to read every number here</h2>
        <BadgeLegend />
        <p className="mt-3 max-w-3xl text-[13px] leading-relaxed text-ink-faint">
          These labels are generated by the data pipeline, not written into the
          interface, so they cannot drift from what was actually measured. Where a
          result was withdrawn or corrected, the{" "}
          <Link href="/methodology/limits" className="text-ink-mute hover:text-accent">
            limits page
          </Link>{" "}
          says so.
        </p>
      </section>
    </div>
  );
}
